# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Personal projects
email: raveious.irw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
excerpt_separator: "<!-- excerpt -->"
github_username: raveious

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji

paginate: 5
paginate_path: "/blog/page:num"

collections:
  shakers:
    output: true
    permalink: /shakers/:title
  tags:
    output: true
    permalink: /blog/tags/:title

defaults:
  - scope:
      type: "posts"
    values:
      permalink: /blog/:year/:month/:day/:title
  - scope:
      type: "shakers"
    values:
      layout: "project"
  - scope:
      type: "tags"
    values:
      layout: "tag"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - .gitignore
  - .travis.yml
  - LICENSE
  - README.md
